import assert from 'node:assert/strict';
import {runAgent} from '../lib/agent';
import {fresh,snapshot} from '../lib/session';
import {env,sqlite} from './mock-runtime';
import reference from '../lib/reference/policy.json';
const session=fresh(),events:any[]=[],bodies:any[]=[];
sqlite.prepare('INSERT INTO demo_sessions(id,payload,busy) VALUES (?,?,1)').run('one',JSON.stringify(session));
const call=(name:string,args:unknown)=>({type:'function_call',call_id:name,name,arguments:JSON.stringify(args)});
const replies=[call('verify_user',{user_id:'U018',email:'customer018@example.com'}),call('get_order',{order_id:'O0011'}),call('create_return',{order_id:'O0011',item_id:'I0011',reason:'change_of_mind',confirmed:true}),{type:'message',content:[{type:'output_text',text:'Please review the exact resolution and approve it in the Cartly app.'}]}];
globalThis.fetch=async(_url:any,options:any)=>{bodies.push(JSON.parse(options.body));const output=replies.shift();assert.ok(output,'No unexpected model request');return Response.json({status:'completed',model:'gpt-6-astra',output:[output],usage:{input_tokens:100,output_tokens:10}})};
await runAgent('one',session,'Yes, please proceed.',e=>events.push(e),new AbortController().signal);
assert.equal(session.verified,'U018');
assert.equal(session.calls,3);
const logs=session.toolLog;assert.equal(logs.length,2);
assert.equal(session.state.returns.length,fresh().state.returns.length);
assert.equal(session.state.refunds.length,fresh().state.refunds.length);
assert.equal(snapshot(session).changes.length,0);
assert.ok(events.some(e=>e.type==='activity'&&e.data.type==='tool'&&e.data.status==='error'));
assert.equal(events.at(-1).type,'done');
assert.ok(bodies.every(b=>b.instructions.startsWith(reference.prompt)&&b.parallel_tool_calls===false&&b.tools.length===8));
assert.ok(!('input' in snapshot(session)));
assert.equal(sqlite.prepare('SELECT busy FROM demo_sessions WHERE id=?').get('one')?.busy,0);
const budget:any=sqlite.prepare('SELECT * FROM demo_budget').get();assert.equal(budget.reserved,0);assert.equal(budget.spent,session.cost);
const clean=fresh();assert.equal(clean.verified,null);assert.equal(clean.messages.length,0);assert.equal(snapshot(clean).changes.length,0);
env.DEMO_BUDGET_USD='0';const blocked=fresh(),blockedEvents:any[]=[];const before=bodies.length;
await runAgent('one',blocked,'Hello',e=>blockedEvents.push(e),new AbortController().signal);
assert.equal(bodies.length,before);assert.ok(blockedEvents.some(e=>e.type==='error'&&e.message.includes('spending allowance')));
assert.equal(sqlite.prepare('SELECT busy FROM demo_sessions WHERE id=?').get('one')?.busy,0);
console.log('PASS: streamed agent/tool loop, blocked direct writes, state isolation, private history, cost settlement, spending gate, and lock release. No API requests made.');
