import source from './reference/world.json';
import policy from './reference/policy.json';
export const TOOL_NAMES=['verify_user','get_order','list_orders','search_policy','check_serviceability','get_refund_history','check_evidence','update_address','cancel_order','create_return','issue_refund','issue_coupon','escalate_to_human'];
export const WRITES=new Set(['update_address','cancel_order','create_return','issue_refund','issue_coupon']);
const PUBLIC=new Set(['verify_user','search_policy','check_serviceability']);
const REASONS=new Set(['change_of_mind','damaged','defective','wrong_item']);
const HIDDEN=new Set(['is_unused','claim_reason','claim_reported_at','user_request','requesting_user_id','requested_delivery_address','edge_case']);
const ACCESS='order or item unavailable for this session';
export const clone=<T,>(v:T):T=>structuredClone(v);
export function publicValue(v:any):any{if(Array.isArray(v))return v.map(publicValue);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).filter(([k])=>!HIDDEN.has(k)).map(([k,x])=>[k,publicValue(x)]));return v}
export function freshWorld():any{return {...publicValue(clone(source)),coupons:[],escalations:[]}}
const keys:any={users:'user_id',orders:'order_id',order_items:'item_id',refunds:'refund_id',returns:'return_id',coupons:'coupon_id',escalations:'escalation_id'};
export function changes(a:any,b:any):any[]{const result:any[]=[];for(const table of Object.keys(b).sort()){if(JSON.stringify(a[table])===JSON.stringify(b[table]))continue;const key=keys[table];if(!key){result.push({table,operation:'replace',key:{},values:b[table]});continue}const old=new Map((a[table]||[]).map((r:any)=>[r[key],r])),next=new Map((b[table]||[]).map((r:any)=>[r[key],r]));for(const id of [...new Set([...old.keys(),...next.keys()])].sort()){const before:any=old.get(id),after:any=next.get(id);if(!before)result.push({table,operation:'insert',key:{[key]:id},values:clone(after)});else if(!after)result.push({table,operation:'delete',key:{[key]:id},values:clone(before)});else{const value:any={};for(const k of new Set([...Object.keys(before),...Object.keys(after)]))if(JSON.stringify(before[k])!==JSON.stringify(after[k]))value[k]=after[k]??null;if(Object.keys(value).length)result.push({table,operation:'update',key:{[key]:id},values:clone(value)})}}}return result}
function fail(message:string):never{throw Error(message)}
function nonempty(v:any):boolean{if(typeof v==='string')return !!v.trim();if(Array.isArray(v))return v.some(nonempty);if(v&&typeof v==='object')return Object.values(v).some(nonempty);return v!==null&&v!==undefined&&v!==false}
export class CartlyTools{
 state:any;verified:string|null;logs:any[]=[];
 constructor(state=freshWorld(),verified:string|null=null){this.state=clone(state);this.verified=verified}
 order(id:any){return this.state.orders.find((r:any)=>r.order_id===id&&r.user_id===this.verified)||fail(ACCESS)}
 item(oid:any,iid:any){const o=this.order(oid),i=this.state.order_items.find((r:any)=>r.order_id===oid&&r.item_id===iid);if(!i)fail(ACCESS);return[o,i]}
 refunds(o:any){return this.state.refunds.filter((r:any)=>r.order_id===o.order_id&&r.status==='completed')}
 items(o:any){return this.state.order_items.filter((r:any)=>r.order_id===o.order_id)}
 method(o:any){return o.payment_method==='COD'?'Cartly Wallet':o.payment_method}
 history(){const end=this.state.config.today;const start=new Date(Date.parse(end+'T00:00:00Z')-90*86400000).toISOString().slice(0,10);return this.state.refunds.filter((r:any)=>r.user_id===this.verified&&r.status==='completed'&&r.date>=start&&r.date<=end)}
 id(table:string,prefix:string){let n=1;while(this.state[table].some((r:any)=>r[keys[table]]===prefix+String(n).padStart(4,'0')))n++;return prefix+String(n).padStart(4,'0')}
 amount(o:any,i:any,reason:string){const shipping=reason!=='change_of_mind'&&!this.refunds(o).some((r:any)=>r.shipping_refunded)?o.shipping_fee:0;const base=reason==='cancellation'?this.items(o).reduce((a:number,x:any)=>a+x.price*x.quantity,0):i.price*i.quantity-(reason==='change_of_mind'?99:0);if(base<0)fail('A3/E4: negative refund requires escalation');return {amount:Math.round((base+shipping)*100)/100,shipping_refunded:!!shipping}}
 appendRefund(o:any,i:any,reason:string){const r={refund_id:this.id('refunds','R'),order_id:o.order_id,item_id:i?.item_id??null,user_id:o.user_id,...this.amount(o,i,reason),reason,date:this.state.config.today,status:'completed',method:this.method(o),authorized_by:'agent'};this.state.refunds.push(r);return r}
 claim(a:any){const[o,i]=this.item(a.order_id,a.item_id);if(this.refunds(o).some((r:any)=>r.item_id===i.item_id))fail('item already refunded');if(o.status!=='Delivered')fail('B: return/refund requires Delivered state');if(!REASONS.has(a.reason))fail('reason must be change_of_mind, damaged, defective, or wrong_item');return[o,i]}
 call(name:string,args:any){const before=clone(this.state),identity=this.verified;let result:any;try{if(!TOOL_NAMES.includes(name))fail('unknown tool');if(!PUBLIC.has(name)&&!this.verified)fail('verification required');if(WRITES.has(name)&&args?.confirmed!==true)fail('confirmation required');if(!args||typeof args!=='object'||Array.isArray(args))fail('invalid arguments');result={ok:true,result:publicValue(this.execute(name,args))}}catch(e:any){this.state=before;this.verified=name==='verify_user'?null:identity;result={ok:false,error:{message:e instanceof TypeError?'invalid arguments':e.message}}}this.logs.push({timestamp:this.state.config.reference_datetime,tool_name:name,arguments:clone(args),...clone(result),mode:'unguarded'});return result}
 execute(name:string,a:any):any{switch(name){
 case 'verify_user':{const u=this.state.users.find((r:any)=>r.user_id===a.user_id);if(!u||!((typeof a.email==='string'&&a.email.toLowerCase()===u.email.toLowerCase())||(typeof a.phone==='string'&&a.phone===u.phone)))fail('verification failed');this.verified=a.user_id;return{verified:true,user_id:this.verified}}
 case 'get_order':{const o=this.order(a.order_id);return{order:o,items:this.items(o)}}
 case 'list_orders':return{orders:this.state.orders.filter((r:any)=>r.user_id===this.verified)};
 case 'search_policy':{if(typeof a.query!=='string'||!a.query.trim())fail('query required');const words=a.query.toLowerCase().split(/\s+/).filter(Boolean);const matches=[...policy.policy.matchAll(/^- ([A-H]\d+)\. (.+)$/gm)].filter(m=>m[1]===a.query.trim().toUpperCase()||words.every((w:string)=>(m[1]+' '+m[2]).toLowerCase().includes(w))).map(m=>({rule:m[1],text:m[2]}));return{version:policy.policy.match(/Cartly Customer Support Policy (v[0-9.]+)/)?.[1],matches}}
 case 'check_serviceability':return{pincode:String(a.pincode),serviceable:this.state.serviceable_pincodes.serviceable_pincodes.includes(String(a.pincode))};
 case 'get_refund_history':{if(a.order_id)this.order(a.order_id);const history=this.history();return{refunds:history,qualifying_count:history.filter((r:any)=>REASONS.has(r.reason)).length,cancellation_count:history.filter((r:any)=>r.reason==='cancellation').length,window_days:90,...(a.order_id?{order_refunds:this.refunds(this.order(a.order_id))}:{})}}
 case 'check_evidence':{const[,i]=this.item(a.order_id,a.item_id);return{order_id:a.order_id,item_id:a.item_id,evidence_photo_uploaded:i.evidence_photo_uploaded}}
 case 'update_address':{const o=this.order(a.order_id);if(o.status!=='Placed')fail('D1: address changes require Placed state');if(!a.address||typeof a.address!=='object'||['line1','city','state','pincode','country'].some(k=>typeof a.address[k]!=='string'||!a.address[k].trim()))fail('D3: full address required');if(!this.execute('check_serviceability',{pincode:a.address.pincode}).serviceable)fail('D2: pincode is not serviceable');o.delivery_address=clone(a.address);return{order_id:a.order_id,delivery_address:o.delivery_address}}
 case 'cancel_order':{const o=this.order(a.order_id);if(!['Placed','Packed'].includes(o.status))fail('C1/C2: cancellation requires Placed or Packed state');if(this.refunds(o).length)fail('order already has a refund');const refund=this.appendRefund(o,null,'cancellation');o.status='Cancelled';return{order_id:o.order_id,status:o.status,refund}}
 case 'create_return':{const[o,i]=this.claim(a);if(this.state.returns.some((r:any)=>r.item_id===i.item_id))fail('return already exists');const r={return_id:this.id('returns','T'),order_id:o.order_id,item_id:i.item_id,pickup_status:'scheduled',created_at:this.state.config.reference_datetime,completed_at:null,reason:a.reason};this.state.returns.push(r);return{return:r,refund_amount:this.amount(o,i,a.reason).amount,refund_method:this.method(o),refund_timing:'automatically after pickup completes'}}
 case 'issue_refund':{const[o,i]=this.claim(a);return{refund:this.appendRefund(o,i,a.reason)}}
 case 'issue_coupon':{const o=this.order(a.order_id);const coupon={coupon_id:this.id('coupons','C'),order_id:o.order_id,user_id:o.user_id,amount:100,date:this.state.config.today};this.state.coupons.push(coupon);o.coupon_issued=true;o.coupon_amount+=100;return{coupon}}
 case 'escalate_to_human':{if(a.order_id)this.order(a.order_id);if(a.item_id)this.item(a.order_id,a.item_id);const fields={user_request:a.user_request,facts_found:a.facts_found,rule_triggered:a.rule_triggered,what_user_was_told:a.what_user_was_told};const missing=Object.entries(fields).filter(([,v])=>!nonempty(v)).map(([k])=>k);if(missing.length)fail('G3: nonempty fields required: '+missing.join(', '));const escalation={escalation_id:this.id('escalations','H'),user_id:this.verified,order_id:a.order_id??null,item_id:a.item_id??null,...fields};this.state.escalations.push(escalation);return{escalation,status:'queued_in_memory'}}
 default:return fail('unknown tool')
 }}
}
